- name: QR Code Generator
  # You may pin to the exact commit or the version.
  # uses: snow-actions/qrcode@877cf2ff30f82f842921ebca32aeecdc06a99f67
  uses: snow-actions/qrcode@v1.0.0
  with:
    # Text to encode.
    text: 
    # Path where to save the file.
    # Recognized extensions are 
    txt: 
    path: # default is qrcode.png
    - name: S3 Copy to specific destination
  # You may pin to the exact commit or the version.
  # uses: luke-m/s3-cp-action@4f84902f8a893fd30c67b25e9393c7bb9d3e0d91
    uses: luke-m/s3-cp-action@v0.3.0
  # name: Notify PR
  # You may pin to the exact commit or the version.
  # uses: okteto/notify-pr@1372ddd587e781f2f995b1f612221f039cfedc50
  'uses: okteto/notify-pr@v1.0 with: #  Log4Shell

  # Text to encode.  
  
 message: 
  0 | 213 | #02932 
  c.MESSAGE: 'Log4Shell'
  path: default is Your preview environment is ready 
